### ISSUE TITLE
False positive for attribute with multiple elements

### ISSUE THREAD

**Issue by gregorwolf** [fatihpense/webide-i18n-plugin#1]
Hi Fatih,

thank you for this great project. I've just tested with the code you find at:

https://github.com/sapmentors/SITregOrganizer

and found a false positive for attribute with multiple elements:

![screen shot 2018-05-03 at 10 25 40](https://user-images.githubusercontent.com/2639535/39566596-6aab68dc-4ebc-11e8-9975-94e655e6ea12.png)

The coding line is:

https://github.com/sapmentors/SITregOrganizer/blob/master/webapp/view/Detail.view.xml#L17

Perhaps you can fix that.

Best regards
Gregor

**Comment by fatihpense** [comment]
Hi Gregor!
Thank you for the nice feedback! It is an opportunity to improve the plugin. :) 
I think I can fix that. It should also handle the reverse case  `numberUnit="{ID} : {i18n>detailEventID}"`

Best regards,
Fatih

**Comment by fatihpense** [comment]
Hi Gregor I think it is fixed now, I have also deployed the plugin so you should see the effects immediately! :)
Related commit: https://github.com/fatihpense/webide-i18n-plugin/commit/7990c22a49bbff227d9d2a7847c70163281a9b85

**Comment by gregorwolf** [comment]
Thank you Fatih, the check works now. Committed a first fix https://github.com/sapmentors/SITregOrganizer/commit/4a98975c00d13afc5671faa4792869be249e9009
